# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings_orientation_marker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_SettingsOrientationMarker(object):
    def setupUi(self, SettingsOrientationMarker):
        SettingsOrientationMarker.setObjectName("SettingsOrientationMarker")
        SettingsOrientationMarker.resize(240, 291)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsOrientationMarker.sizePolicy().hasHeightForWidth())
        SettingsOrientationMarker.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsOrientationMarker)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.item_name = QtWidgets.QLabel(SettingsOrientationMarker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name.sizePolicy().hasHeightForWidth())
        self.item_name.setSizePolicy(sizePolicy)
        self.item_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.item_name.setObjectName("item_name")
        self.verticalLayout.addWidget(self.item_name)
        self.layout_size = QtWidgets.QHBoxLayout()
        self.layout_size.setObjectName("layout_size")
        self.label_size = QtWidgets.QLabel(SettingsOrientationMarker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_size.sizePolicy().hasHeightForWidth())
        self.label_size.setSizePolicy(sizePolicy)
        self.label_size.setObjectName("label_size")
        self.layout_size.addWidget(self.label_size)
        self.edit_width = QtWidgets.QLineEdit(SettingsOrientationMarker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_width.sizePolicy().hasHeightForWidth())
        self.edit_width.setSizePolicy(sizePolicy)
        self.edit_width.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edit_width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_width.setObjectName("edit_width")
        self.layout_size.addWidget(self.edit_width)
        self.label_unit = QtWidgets.QLabel(SettingsOrientationMarker)
        self.label_unit.setObjectName("label_unit")
        self.layout_size.addWidget(self.label_unit)
        self.verticalLayout.addLayout(self.layout_size)
        self.checkbox_save_keyframes = QtWidgets.QCheckBox(SettingsOrientationMarker)
        self.checkbox_save_keyframes.setChecked(True)
        self.checkbox_save_keyframes.setObjectName("checkbox_save_keyframes")
        self.verticalLayout.addWidget(self.checkbox_save_keyframes)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SettingsOrientationMarker)
        QtCore.QMetaObject.connectSlotsByName(SettingsOrientationMarker)

    def retranslateUi(self, SettingsOrientationMarker):
        _translate = QtCore.QCoreApplication.translate
        SettingsOrientationMarker.setWindowTitle(_translate("SettingsOrientationMarker", "Form"))
        self.item_name.setText(_translate("SettingsOrientationMarker", "Orientation Marker"))
        self.label_size.setText(_translate("SettingsOrientationMarker", "Width"))
        self.edit_width.setText(_translate("SettingsOrientationMarker", "20"))
        self.label_unit.setText(_translate("SettingsOrientationMarker", "% of screen"))
        self.checkbox_save_keyframes.setText(_translate("SettingsOrientationMarker", "Save to keyframes"))
